FROM nginx:alpine
# copie du build Angular
COPY dist/ /usr/share/nginx/html
# remplace la conf par défaut du conteneur pour proxifier /api vers le service "api"
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80