name: Quality + Sync GitLab

# workflow a le droit de créer des checks & des PR (nécessaire pr rapports Dorny)
permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["**"]

jobs:
  # lance tests uniquement sur dossier modifié
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Filter paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

  quality-backend:
    name: Backend - Tests & SonarCloud
    runs-on: ubuntu-latest

    # Lancé uniquement si backend modifié
    needs: changes
    if: needs.changes.outputs.backend == 'true'

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # requis pour Sonar

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Tests unitaires & tests d'intégration
      - name: Run backend tests (unit + IT) with coverage
        run: mvn -B clean verify

      - name: SonarCloud Scan (Backend)
        if: github.ref == 'refs/heads/main'
        run: mvn -B sonar:sonar # Propriétés définies dans le pom.xml
        continue-on-error: true # Rend le Quality Gate non bloquant
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pour PR decoration

      - name: Publish Backend Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Backend Tests
          path: backend/target/*-reports/TEST-*.xml
          reporter: java-junit

  quality-frontend:
    name: Frontend - Tests & SonarCloud
    runs-on: ubuntu-latest

    # Lancé uniquement si frontend modifié
    needs: changes
    if: needs.changes.outputs.frontend == 'true'

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Run frontend tests with coverage
        run: npm run test:ci
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }} # chemin dynamique

      - name: SonarCloud Scan (Frontend)
        # Limite l'analyse Sonar à la branche main
        if: github.ref == 'refs/heads/main'
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true #Rend le Quality Gate non bloquant
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: frontend
          args: >
            -Dsonar.projectKey=pololac_powerme_front
            -Dsonar.organization=pololac

      - name: Publish Frontend Test Results
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Frontend Tests
          path: frontend/test-results/junit.xml
          reporter: java-junit

  sync-gitlab:
    name: Sync to GitLab
    runs-on: ubuntu-latest

    needs: [changes, quality-backend, quality-frontend]

    # Synchronisation GitLab uniquement sur push vers main,
    # si les jobs de qualité n'ont pas échoué (skippés ou réussis = OK)
    if: |
      always() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      needs.quality-backend.result != 'failure' &&
      needs.quality-frontend.result != 'failure'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Push to GitLab
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_USER: ${{ secrets.USERNAME }}
          GITLAB_PAT: ${{ secrets.GITLAB_PAT }}
        run: |
          git remote add gitlab "https://${GITLAB_USER}:${GITLAB_PAT}@${GITLAB_URL#https://}"
          git push gitlab main --force
