include:
  - local: .gitlab/ci/build-template.yml
  - local: .gitlab/ci/deploy-template.yml

stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: 20
  FRONTEND_IMAGE: $CI_REGISTRY_IMAGE/frontend
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

cache:
  key:
    files:
      - package-lock.json # Cache invalidé si package-lock.json change
  paths:
    - .npm/ # Évite de re-télécharger les packages

##############################################
# TESTS Jasmine
##############################################
frontend-tests:
  stage: test
  image: node:20-bookworm
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feat\/.*/'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

  before_script:
    - apt-get update
    - apt-get install -y chromium
    - export CHROME_BIN=/usr/bin/chromium

  script:
    - cd frontend
    - npm ci
    - npm run test:ci

  coverage: '/Statements\s*:\s*(\d+\.?\d*)%/' # UI GitLab
  artifacts:
    when: always
    reports:
      junit: coverage/junit.xml
    paths:
      - coverage/
    expire_in: 1 week
  allow_failure: false

##############################################
# BUILD FRONTEND (Docker)
##############################################
build-frontend:
  extends: .build-docker-template

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - job: frontend-tests
      artifacts: true

  variables:
    BUILD_CONTEXT: frontend
    IMAGE_NAME: $FRONTEND_IMAGE
    BUILD_ARG_NAME: NODE_VERSION
    BUILD_ARG_VALUE: $NODE_VERSION

##############################################
# DEPLOY
##############################################
deploy-frontend:
  extends: .deploy-template

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - build-frontend

  variables:
    SERVICE: frontend
    PROFILE: frontend # Déploie frontend + nginx

