include:
  - local: .gitlab/ci/build-template.yml
  - local: .gitlab/ci/deploy-template.yml

stages:
  - test
  - build
  - deploy

variables:
  MAVEN_VERSION: 3.9.11
  JAVA_VERSION: 21
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  BACKEND_IMAGE: $CI_REGISTRY_IMAGE/backend
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

# Définit le cache global avec une anchor (&maven-cache)
.maven-cache: &maven-cache
  key:
    files:
      - backend/pom.xml
  paths:
    - .m2/repository
  policy: pull-push
  when: on_success

# Applique le cache globalement
cache: *maven-cache

.backend-test-base:
  image: maven:${MAVEN_VERSION}-eclipse-temurin-${JAVA_VERSION}-alpine
  cache:
    <<: *maven-cache # Référence au cache global
  artifacts:
    when: always
    # Exporter les classes compilées pour SonarCloud
    paths:
      - backend/target/classes/
      - backend/target/test-classes/
    expire_in: 1 week

##############################################
# TESTS UNITAIRES
##############################################
backend-unit-tests:
  stage: test
  extends: .backend-test-base

  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^feat\/.*/'
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

  script:
    - mvn -B -f backend/pom.xml clean test

  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    reports:
      junit: backend/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: backend/target/site/jacoco/jacoco.xml
    paths:
      # Rapports pour SonarCloud
      - backend/target/surefire-reports/
      - backend/target/site/jacoco/

  allow_failure: false

##############################################
# TESTS D’INTÉGRATION (Testcontainers)
##############################################
backend-integration-tests:
  stage: test
  extends: .backend-test-base

  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_COMMIT_BRANCH == "main"'

  services: # Nécessaire pr BDD tests via Testcontainers en Docker
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_HOST: "tcp://docker:2375" # Permet à Testcontainers de communiquer avec Docker-in-Docker
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    TESTCONTAINERS_HOST_OVERRIDE: "docker" # Force Testcontainers à utiliser le service Docker
    TESTCONTAINERS_RYUK_DISABLED: "false" # Ryuk doit être activé en DinD
    TESTCONTAINERS_CHECKS_DISABLE: "true" # Accélère

  needs:
    - job: backend-unit-tests
      artifacts: true

  before_script:
    # Installe docker-cli (pas ds Alpine Maven) et vérifie que Docker est prêt
    - apk add --no-cache docker-cli
    - |
      echo "⏳ Attente du daemon Docker..."
      for i in $(seq 1 30); do
        if docker info > /dev/null 2>&1; then
          echo "✅ Docker prêt!"
          break
        fi
        echo "Waiting for Docker... ($i/30)"
        sleep 2
      done
    - docker info # Vérifier que Docker fonctionne

  script:
    - mvn -B -f backend/pom.xml verify -DskipTests

  artifacts:
    when: always
    reports:
      junit: backend/target/failsafe-reports/TEST-*.xml
    paths:
      - backend/target/failsafe-reports/
  allow_failure: false

##############################################
# BUILD BACKEND (Docker)
##############################################
build-backend:
  extends: .build-docker-template
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    BUILD_CONTEXT: backend
    IMAGE_NAME: $BACKEND_IMAGE
    BUILD_ARG_NAME: JAVA_VERSION
    BUILD_ARG_VALUE: $JAVA_VERSION
  needs:
    - job: backend-unit-tests
      artifacts: true
    - job: backend-integration-tests
      artifacts: true
  after_script:
    - |
      echo "🔍 Vérification de l'image buildée..."
      docker run --rm ${BACKEND_IMAGE}:${IMAGE_TAG} java -version

##############################################
# DEPLOY
##############################################
deploy-backend:
  extends: .deploy-template
  variables:
    SERVICE: backend
    PROFILE: backend # Déploie backend + db
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - build-backend
